# Generated by Django 2.1.7 on 2020-04-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(db_column='id_usuario', primary_key=True, serialize=False),
        ),
    ]
